# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.24"
  amd64: "ghcr.io/home-assistant/amd64-base:3.24"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Sherpa Streaming STT"
  org.opencontainers.image.description: "Generic multi-model streaming speech-to-text for Home Assistant using sherpa-onnx."
  org.opencontainers.image.source: "https://github.com/h3llrais3r/hassio-addons/tree/master/sherpa-streaming-stt"
  org.opencontainers.image.licenses: "MIT"
args:
  SHERPA_ONNX_VERSION: "1.13.8"
  WYOMING_VERSION: "1.10.2"
