# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
  armhf: "ghcr.io/home-assistant/armhf-base:3.22"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"
  i386: "ghcr.io/home-assistant/i386-base:3.22"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: AdguardHome Sync"
  org.opencontainers.image.description: "Synchronize your main AdGuard Home configuration to one or more replica instances."
  org.opencontainers.image.source: "https://github.com/h3llrais3r/hassio-addons/tree/master/adguardhome-sync"
  org.opencontainers.image.licenses: "MIT"
args:
  ADGUARDHOME_SYNC_VERSION: "0.8.1"
