# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: AdGuardHome Sync
version: "0.1.0"
slug: adguardhome_sync
description: Synchronize AdGuard Home configuration from an origin instance to one or more replica instances.
url: https://github.com/h3llrais3r/hassio-addons/adguardhome-sync
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
init: false
startup: services
boot: auto
options:
  cron: "*/5 * * * *"
  run_on_start: true
  continue_on_error: false
  origin_url: ""
  origin_username: ""
  origin_password: ""
  replicas:
    - url: ""
      username: ""
      password: ""
schema:
  cron: str
  run_on_start: bool
  continue_on_error: bool
  origin_url: str
  origin_username: str?
  origin_password: str?
  replicas:
    - url: str
      username: str?
      password: str?
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web/API UI port
