name: Changelog generator

on:
  push:
    branches:
      - master

jobs:
  generate-changelogs:
    if: github.actor != 'github-actions[bot]' # Prevent self-trigger from changelog commits from this action
    name: Generate changelogs
    runs-on: ubuntu-latest
    steps:
      # Checkout repository with full history
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # Fetch all commits to enable HEAD~1

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install -g auto-changelog
          sudo apt-get update && sudo apt-get install -y yq

      # Detect root-level addon folders
      - name: Detect addon folders
        id: addons
        run: |
          ADDON_DIRS=$(find . -maxdepth 1 -mindepth 1 -type d ! -name ".*")
          echo "addons=$ADDON_DIRS" >> $GITHUB_OUTPUT

      # Generate CHANGELOG.md per addon
      - name: Generate CHANGELOG.md per addon
        run: |
          for ADDON_PATH in ${{ steps.addons.outputs.addons }}; do
            echo "Processing $ADDON_PATH"

            # Skip if nothing changed in source/config files (excluding CHANGELOG.md)
            CHANGES=$(git diff --name-only HEAD~1 HEAD "$ADDON_PATH" | grep -v "CHANGELOG.md" || true)
            if [ -z "$CHANGES" ]; then
              echo "No source/config changes in $ADDON_PATH, skipping changelog generation"
              continue
            fi

            CONFIG_FILE="$ADDON_PATH/config.yaml"
            SKIP_COMMIT=false
            if [ -f "$CONFIG_FILE" ]; then
              # Safely get OLD_VERSION, fallback if HEAD~1 doesn't exist
              if git rev-parse HEAD~1 >/dev/null 2>&1; then
                OLD_VERSION=$(git show HEAD~1:"$CONFIG_FILE" 2>/dev/null | yq e '.version' -)
              else
                OLD_VERSION=""
              fi
              # Get NEW_VERSION from the current HEAD
              NEW_VERSION=$(git show HEAD:"$CONFIG_FILE" 2>/dev/null | yq e '.version' -)
              # Skip changelog generation if this commit is a release commit
              if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
                echo "Release commit detected in $CONFIG_FILE, skipping changelog generation for this commit"
                SKIP_COMMIT=true
              fi
            fi
            if [ "$SKIP_COMMIT" = true ]; then
              continue
            fi

            # Paths for temporary and target changelog
            TEMP="$ADDON_PATH/CHANGELOG_temp.md"
            TARGET="$ADDON_PATH/CHANGELOG.md"
            mkdir -p "$(dirname "$TARGET")"

            # Ensure CHANGELOG.md exists
            if [ ! -f "$TARGET" ]; then
              echo -e "## [Unreleased]\n" > "$TARGET"
            fi

            # Generate new changelog entries from commits affecting this folder
            auto-changelog -p \
              --commit-limit false \
              --unreleased-only true \
              --output "$TEMP" \
              --commit-filter "git log --pretty=format:'%H' -- $ADDON_PATH -- . ':(exclude)CHANGELOG.md'"

            # Prepend new entries under [Unreleased]
            awk -v temp="$TEMP" '
              BEGIN {while ((getline line < temp) > 0) {newlines = newlines line "\n"}}
              /^## \[Unreleased\]/ {print; print newlines; next}1
            ' "$TARGET" > "$TARGET.tmp" && mv "$TARGET.tmp" "$TARGET"

            # Commit only if there are staged changes
            git add "$TARGET"
            if ! git diff --cached --quiet; then
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git commit -m "Update $ADDON_PATH/CHANGELOG.md"
            else
                echo "No new changes to commit for $ADDON_PATH"
            fi
          done

      # Push all commits (rebase to avoid conflicts for already other commits)
      - name: Push commits
        run: |
          git fetch origin master
          git rebase origin/master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
